# Generated by Django 6.0.6 on 2026-06-10 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_payments"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="s_active",
            new_name="is_active",
        ),
    ]
