# Generated by Django 6.0.6 on 2026-06-17 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
