# Generated by Django 6.0.6 on 2026-06-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_managers_remove_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="link",
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name="Ссылка на платеж"),
        ),
        migrations.AddField(
            model_name="payments",
            name="session_id",
            field=models.CharField(
                blank=True, help_text="Укажите session_id", max_length=50, null=True, verbose_name="session_id"
            ),
        ),
    ]
