# Generated by Django 6.0.6 on 2026-06-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_payments_link_payments_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="link",
            field=models.URLField(blank=True, max_length=800, null=True, verbose_name="Ссылка на платеж"),
        ),
    ]
