# Generated by Django 6.0.6 on 2026-06-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_payments_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="session_id",
            field=models.CharField(
                blank=True, help_text="Укажите session_id", max_length=200, null=True, verbose_name="session_id"
            ),
        ),
    ]
