# Generated by Django 6.0.6 on 2026-06-17 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_subscriptions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptions",
            name="user",
        ),
        migrations.AlterField(
            model_name="subscriptions",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_subscriptions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ученик",
            ),
        ),
    ]
