name: Django CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.14'

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry==2.2.1

      - name: Install flake8
        run: poetry add flake8

      - name: Run flake8
        run: poetry run flake8 .

  test:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.14'

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry==2.2.1

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-root

      - name: Run test
        env:
          SECRET_KEY: 'test-secret-key-for-github-actions'
          LANGUAGE: 'ru'
          LC_ALL: 'ru_RU.UTF-8'
          CELERY_TASK_ALWAYS_EAGER: 'True'
        run: poetry run python manage.py test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_NAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_NAME }}/hw_35:${{ github.sha }} -t ${{ secrets.DOCKER_HUB_NAME }}/hw_35:latest .

      - name: Push Docker image to Docker Hub
        run: docker push --all-tags ${{ secrets.DOCKER_HUB_NAME }}/hw_35

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Remote Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: admin-vm1
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            
            if ! command -v docker &> /dev/null; then
              echo "Docker не найден. Принудительно очищаем старый кэш репозиториев..."
            
              
              sudo rm -f /etc/apt/sources.list.d/docker*.list
              sudo rm -f /etc/apt/sources.list.d/ubuntu.sources
              sudo rm -f /etc/apt/sources.list
            
              
              sudo tee /etc/apt/sources.list.d/ubuntu.sources << 'EOF'
            Types: deb
            URIs: http://yandex.ru
            Suites: noble noble-updates noble-backports noble-security
            Components: main restricted universe multiverse
            Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
            EOF
            
              
              sudo rm -rf /var/lib/apt/lists/*
            
              echo "Запускаем установку Docker через официальный скрипт..."
              wget -qO- https://get.docker.com | sh
            
              
              sudo groupadd docker || true
              sudo usermod -aG docker admin-vm1
            
              echo "Docker успешно установлен!"
            fi
            
            
            echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_NAME }}" --password-stdin
            
            
            docker pull ${{ secrets.DOCKER_HUB_NAME }}/hw_35:${{ github.sha }}
            
            
            docker stop myapp-container || true
            docker rm myapp-container || true
            
            
            docker run -d \
              --name myapp-container \
              -p 8000:8000 \
              --restart unless-stopped \
              ${{ secrets.DOCKER_HUB_NAME }}/hw_35:${{ github.sha }}
            
            
            docker image prune -f